name: Deploy automático al servidor

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el repositorio
      uses: actions/checkout@v3

    - name: Actualizar código en el servidor
      run: |
        ssh -p 2222 empire@88.8.43.131 "cd ~/Documentos/github/MatuChio-WEB-Estable && git pull"
